### ISSUE TITLE
License file need.

### ISSUE THREAD

**Issue by ghost** [frostglitch/borderhunt#22]
Yes we should add a license file.
Because someday we will make this project public.

**Comment by frostglitch** [comment]
@nosferatu255 Check this out: https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project

**Comment by nosferatu255** [comment]
Yes, i shall in the future.

**Comment by ghost** [comment]
There i have added the MIT License. https://github.com/frostglitch/borderhunt/blob/main/LICENSE
And also i added the license link into our README file.

**Comment by frostglitch** [comment]
Sick 💪🏻💪🏻
